from keyboarlayout.key import Key as KlKey

import pygame

class PygameKey(int):
    pass

__KEY_TO_KL_KEY = {
    pygame.K_BACKQUOTE: KlKey.K_BACKQUOTE,
    pygame.K_BACKQUOTE: KlKey.K_BACKQUOTE,
    pygame.K_1: KlKey.K_1,
    pygame.K_2: KlKey.K_2,
    pygame.K_3: KlKey.K_3,
    pygame.K_4: KlKey.K_4,
    pygame.K_5: KlKey.K_5,
    pygame.K_6: KlKey.K_6,
    pygame.K_7: KlKey.K_7,
    pygame.K_8: KlKey.K_8,
    pygame.K_9: KlKey.K_9,
    pygame.K_0: KlKey.K_0,
    pygame.K_MINUS: KlKey.K_MINUS,
    pygame.K_EQUALS: KlKey.K_EQUALS,
    pygame.K_BACKSPACE: KlKey.K_BACKSPACE,
    pygame.K_TAB: KlKey.K_TAB,
    pygame.K_Q: KlKey.K_Q,
    pygame.K_W: KlKey.K_W,
    pygame.K_E: KlKey.K_E,
    pygame.K_R: KlKey.K_R,
    pygame.K_T: KlKey.K_T,
    pygame.K_Y: KlKey.K_Y,
    pygame.K_U: KlKey.K_U,
    pygame.K_I: KlKey.K_I,
    pygame.K_O: KlKey.K_O,
    pygame.K_P: KlKey.K_P,
    pygame.K_LEFTBRACKET: KlKey.K_LEFTBRACKET,
    pygame.K_RIGHTBRACKET: KlKey.K_RIGHTBRACKET,
    pygame.K_BACKSLASH: KlKey.K_BACKSLASH,
    pygame.K_CAPSLOCK: KlKey.K_CAPSLOCK,
    pygame.K_A: KlKey.K_A,
    pygame.K_S: KlKey.K_S,
    pygame.K_D: KlKey.K_D,
    pygame.K_F: KlKey.K_F,
    pygame.K_G: KlKey.K_G,
    pygame.K_H: KlKey.K_H,
    pygame.K_J: KlKey.K_J,
    pygame.K_K: KlKey.K_K,
    pygame.K_L: KlKey.K_L,
    pygame.K_SEMICOLON: KlKey.K_SEMICOLON,
    pygame.K_DOUBLEQUOTE: KlKey.K_DOUBLEQUOTE,
    pygame.K_RETURN: KlKey.K_RETURN,
    pygame.K_LEFTSHIFT: KlKey.K_LEFT_SHIFT,
    pygame.K_Z: KlKey.K_Z,
    pygame.K_X: KlKey.K_X,
    pygame.K_C: KlKey.K_C,
    pygame.K_V: KlKey.K_V,
    pygame.K_B: KlKey.K_B,
    pygame.K_N: KlKey.K_N,
    pygame.K_M: KlKey.K_M,
    pygame.K_COMMA: KlKey.K_COMMA,
    pygame.K_PERIOD: KlKey.K_PERIOD,
    pygame.K_FORWARDSLASH: KlKey.K_FORWARDSLASH,
    pygame.K_RIGHTSHIFT: KlKey.K_RIGHT_SHIFT,
    pygame.K_LCTRL: KlKey.K_LEFT_CONTROL,
    pygame.K_LMETA: KlKey.K_LEFT_META,
    pygame.K_LALT: KlKey.K_LEFT_ALT,
    pygame.K_SPACE: KlKey.K_SPACE,
    pygame.K_RALT: KlKey.K_RIGHT_ALT,
    pygame.K_RMETA: KlKey.K_RIGHT_META,
    pygame.K_COMPOSE: KlKey.K_COMPOSE,
    pygame.K_RCTRL: KlKey.K_RCTRL,
}

def get_key(key: PygameKey) -> KlKey:
    return __KEY_TO_KL_KEY[key]
