from enum import Enum

class Key(Enum):
    """
    These are generic platform independent key constants
    Each graphics backend maps from its own specific key codes to
    these constants
    """
    K_BACKQUOTE = '`'
    K_1 = '1'
    K_2 = '2'
    K_3 = '3'
    K_4 = '4'
    K_5 = '5'
    K_6 = '6'
    K_7 = '7'
    K_8 = '8'
    K_9 = '9'
    K_0 = '0'
    K_MINUS = '-'
    K_EQUALS = '='
    K_BACKSPACE = 'backspace'
    K_TAB = 'tab'
    K_Q = 'q'
    K_W = 'w'
    K_E = 'e'
    K_R = 'r'
    K_T = 't'
    K_Y = 'y'
    K_U = 'u'
    K_I = 'i'
    K_O = 'o'
    K_P = 'p'
    K_LEFTPAREN = '('
    K_RIGHTPAREN = ')'
    K_LEFTBRACKET = '['
    K_RIGHTBRACKET = ']'
    K_BACKSLASH = '\\'
    K_CAPSLOCK = 'caps lock'
    K_A = 'a'
    K_S = 's'
    K_D = 'd'
    K_F = 'f'
    K_G = 'g'
    K_H = 'h'
    K_J = 'j'
    K_K = 'k'
    K_L = 'l'
    K_SEMICOLON = ';'
    K_DOUBLEQUOTE = '"'
    K_SINGLEQUOTE = "'"
    K_RETURN = 'return'
    K_LESSTHAN = '<'
    K_LEFT_SHIFT = 'left shift'
    K_Z = 'z'
    K_X = 'x'
    K_C = 'c'
    K_V = 'v'
    K_B = 'b'
    K_N = 'n'
    K_M = 'm'
    K_COMMA = ','
    K_PERIOD = '.'
    K_FORWARDSLASH = '/'
    K_RIGHT_SHIFT = 'right shift'
    K_LEFT_CONTROL = 'left ctrl'
    K_LEFT_META = 'left meta'
    K_LEFT_ALT = 'left alt'
    K_SPACE = 'space'
    K_RIGHT_ALT = 'right alt'
    K_RIGHT_META = 'right meta'
    K_CONTEXT_MENU = 'context menu'  # windows key
    K_RIGHT_CONTROL = 'right ctrl'
    K_CARET = '^'
    K_DOLLAR = '$'
    K_U_GRAVE = 'ù'
    K_ASTERISK = '*'
    K_COLON = ':'
    K_EXCLAMATION = '!'
    K_FUNCTION = 'function'
    K_LEFT_ARROW = 'left arrow'
    K_RIGHT_ARROW = 'right arrow'
    K_UP_ARROW = 'up arrow'
    K_DOWN_ARROW = 'down arrow'
    K_AMPERSAND = '&'
    K_E_ACUTE = 'é'
    K_E_GRAVE = 'è'
    K_UNDERSCORE = '_'
    K_C_CEDILLE = 'ç'
    K_A_GRAVE = 'à'
